'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useUserPals } from '../../../hooks/useUserPals';
import { pals } from '../../../data/pals';
import { findBreedingPath, PathStep } from '../../../utils/breedingPathfinder';
import { SelectField } from '../../../components/ui/SelectField';
import { BreedingTree } from '../../../components/breeding/BreedingTree';
import { Copy, List, Network } from 'lucide-react';

export default function BreedingPathfinder() {
  const { pals: savedPals } = useUserPals();
  const [tempPals, setTempPals] = useState<string[]>([]);
  const [targetKey, setTargetKey] = useState<string>(pals[0].key);
  const [path, setPath] = useState<PathStep[] | null>(null);
  const [searching, setSearching] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'list' | 'tree'>('tree');

  const availableKeys = Array.from(new Set([
    ...savedPals.map(p => p.palKey),
    ...tempPals
  ]));

  const handleSearch = () => {
    setSearching(true);
    setError(null);
    setPath(null);

    // Allow UI to update before blocking
    setTimeout(() => {
      try {
        const result = findBreedingPath(availableKeys, targetKey);
        if (result && result.length > 0) {
          setPath(result);
        } else {
          setError('No breeding path found within 5 generations. Try adding more variety to your available Pals.');
        }
      } catch (e) {
        console.error(e);
        setError('An unexpected error occurred.');
      } finally {
        setSearching(false);
      }
    }, 50);
  };

  const handleExport = () => {
    if (!path) return;
    const lines = path.map((step, i) =>
        step.generation === 0
          ? `You already own ${step.result.name}.`
          : `${i+1}. ${step.parent1?.name || 'Base'} + ${step.parent2?.name || 'Base'} -> ${step.result.name}`
    );
    const text = `Breeding Plan for ${pals.find(p => p.key === targetKey)?.name}:\n\n${lines.join('\n')}\n\nGenerated by Palworld Companion`;
    navigator.clipboard.writeText(text);
    alert('Breeding plan copied to clipboard!');
  };

  const palOptions: [string, string][] = pals.map(p => [p.key, p.name]);

  // Options for temp add
  const addOptions = palOptions.filter(([k]) => !tempPals.includes(k));

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold mb-2 text-[var(--color-brand-text-primary)]">Breeding Pathfinder</h1>
        <p className="text-[var(--color-brand-text-secondary)]">
          Find the shortest breeding chain to get your dream Pal using Pals you already own.
        </p>
      </div>

      <div className="grid gap-8 lg:grid-cols-3">
        {/* Left Column: Input */}
        <div className="lg:col-span-1 space-y-6 card p-6 h-fit">
          <div>
            <h2 className="text-xl font-bold text-[var(--color-brand-primary)] mb-4 flex items-center gap-2">
              <span>Your Roster</span>
              <span className="text-xs bg-[var(--color-brand-bg-sidebar)] text-[var(--color-brand-text-primary)] px-2 py-0.5 rounded-full border border-[var(--color-brand-border)]">{availableKeys.length}</span>
            </h2>

            <div className="text-sm text-[var(--color-brand-text-secondary)] mb-4 flex items-center justify-between">
              <span>Includes {savedPals.length} from your box.</span>
              <Link href="/my-pals" className="text-[var(--color-brand-primary)] hover:text-[var(--color-brand-primary-hover)] underline font-semibold text-xs">
                Manage Box →
              </Link>
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold text-[var(--color-brand-text-muted)] uppercase tracking-wider">Add Temporary Pal</label>
              <select
                className="w-full px-3 py-2 bg-[var(--color-brand-bg-main)] border border-[var(--color-brand-border)] rounded-lg text-sm text-[var(--color-brand-text-primary)] focus:ring-2 focus:ring-[var(--color-brand-primary)]"
                onChange={(e) => {
                  const val = e.target.value;
                  if (val && !tempPals.includes(val)) {
                    setTempPals([...tempPals, val]);
                  }
                }}
                value=""
              >
                <option value="">+ Add Species...</option>
                {addOptions.map(([k, n]) => (
                  <option key={k} value={k}>{n}</option>
                ))}
              </select>

              {tempPals.length > 0 && (
                <div className="flex flex-wrap gap-2 mt-3 p-3 bg-[var(--color-brand-bg-main)]/50 rounded-lg border border-[var(--color-brand-border)]">
                  {tempPals.map(k => {
                    const p = pals.find(x => x.key === k);
                    return (
                      <span key={k} className="inline-flex items-center gap-1.5 bg-[var(--color-brand-bg-card)] text-[var(--color-brand-text-secondary)] text-xs px-2 py-1 rounded border border-[var(--color-brand-border)]">
                        {p?.name}
                        <button
                          onClick={() => setTempPals(tempPals.filter(x => x !== k))}
                          className="hover:text-red-400 font-bold ml-1"
                        >
                          ×
                        </button>
                      </span>
                    );
                  })}
                </div>
              )}
            </div>
          </div>

          <div className="pt-6 border-t border-[var(--color-brand-border)]">
            <SelectField
              label="Target Pal"
              value={targetKey}
              onChange={setTargetKey}
              options={palOptions}
            />
          </div>

          <button
            onClick={handleSearch}
            disabled={searching || availableKeys.length === 0}
            className={`
              w-full btn-primary
              ${availableKeys.length === 0 ? 'opacity-50 cursor-not-allowed' : ''}
              ${searching ? 'cursor-wait' : ''}
            `}
          >
            {searching ? 'Calculating...' : 'Find Breeding Path'}
          </button>
        </div>

        {/* Right Column: Result */}
        <div className="lg:col-span-2">
          <div className="card p-6 min-h-[500px]">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 border-b border-[var(--color-brand-border)] pb-4">
                <h2 className="text-xl font-bold text-[var(--color-brand-primary)]">
                Breeding Chain
                </h2>

                {path && (
                    <div className="flex items-center gap-2">
                        <div className="flex bg-[var(--color-brand-bg-main)] rounded-lg p-1 border border-[var(--color-brand-border)]">
                            <button
                                onClick={() => setViewMode('tree')}
                                className={`flex items-center gap-2 px-3 py-1.5 rounded-md transition-colors ${viewMode === 'tree' ? 'bg-[var(--color-brand-bg-card)] text-[var(--color-brand-primary)] font-bold shadow-sm' : 'text-[var(--color-brand-text-muted)] hover:text-[var(--color-brand-text-primary)]'}`}
                                title="Visual Tree Map"
                            >
                                <Network size={16} />
                                <span className="text-xs">Tree Map</span>
                            </button>
                            <div className="w-px bg-[var(--color-brand-border)] my-1"></div>
                            <button
                                onClick={() => setViewMode('list')}
                                className={`flex items-center gap-2 px-3 py-1.5 rounded-md transition-colors ${viewMode === 'list' ? 'bg-[var(--color-brand-bg-card)] text-[var(--color-brand-primary)] font-bold shadow-sm' : 'text-[var(--color-brand-text-muted)] hover:text-[var(--color-brand-text-primary)]'}`}
                                title="List Steps"
                            >
                                <List size={16} />
                                <span className="text-xs">List</span>
                            </button>
                        </div>
                        <button
                            onClick={handleExport}
                            className="btn-secondary text-xs py-1.5 px-3 flex items-center gap-1.5"
                        >
                            <Copy size={14} /> Export
                        </button>
                    </div>
                )}
            </div>

            {error && (
              <div className="p-4 bg-red-900/20 border border-red-900/50 rounded-lg text-red-200 flex items-start gap-3">
                <span className="text-2xl">⚠️</span>
                <div>
                  <div className="font-bold">Path Not Found</div>
                  <div className="text-sm opacity-80">{error}</div>
                </div>
              </div>
            )}

            {!path && !searching && !error && (
              <div className="flex flex-col items-center justify-center h-[300px] text-[var(--color-brand-text-muted)]">
                <div className="text-4xl mb-4 opacity-30">🧬</div>
                <p>Select your available Pals and a target to start.</p>
              </div>
            )}

            {searching && (
              <div className="flex flex-col items-center justify-center h-[300px] text-[var(--color-brand-primary)] animate-pulse">
                <div className="text-4xl mb-4">🔍</div>
                <p>Searching for optimal breeding path...</p>
              </div>
            )}

            {path && (
                <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                    {path.length === 1 && path[0].generation === 0 ? (
                        <div className="flex flex-col items-center justify-center p-8 bg-green-900/10 border border-green-500/20 rounded-xl text-green-400">
                             <div className="text-4xl mb-4">🎉</div>
                             <h3 className="text-xl font-bold mb-2">You already own {path[0].result.name}!</h3>
                             <p className="opacity-70">No breeding necessary.</p>
                        </div>
                    ) : (
                        viewMode === 'list' ? (
                            <div className="space-y-6 relative ml-4 pl-8 border-l-2 border-[var(--color-brand-border)] py-2">
                                {path.map((step, idx) => (
                                <div key={idx} className="relative group">
                                    <div className="absolute -left-[43px] top-1/2 -translate-y-1/2 w-8 h-8 rounded-full bg-[var(--color-brand-bg-card)] border-2 border-[var(--color-brand-border)] flex items-center justify-center font-bold text-[var(--color-brand-text-secondary)] group-hover:border-[var(--color-brand-primary)] group-hover:text-[var(--color-brand-primary)] transition-colors z-10">
                                    {idx + 1}
                                    </div>

                                    <div className="bg-[var(--color-brand-bg-main)]/50 p-4 rounded-xl border border-[var(--color-brand-border)] shadow-sm hover:border-[var(--color-brand-primary)]/30 transition-colors">
                                    <div className="flex flex-col md:flex-row items-center justify-between gap-4">

                                        {/* Parents */}
                                        <div className="flex items-center gap-3 flex-1 justify-end md:justify-start w-full md:w-auto">
                                        <div className="flex items-center gap-2 bg-[var(--color-brand-bg-card)] px-3 py-1.5 rounded-lg border border-[var(--color-brand-border)]">
                                            <span className="w-2 h-2 rounded-full bg-slate-500"></span>
                                            <span className="font-semibold text-[var(--color-brand-text-primary)]">{step.parent1?.name}</span>
                                        </div>
                                        <span className="text-[var(--color-brand-text-muted)] font-bold text-lg">+</span>
                                        <div className="flex items-center gap-2 bg-[var(--color-brand-bg-card)] px-3 py-1.5 rounded-lg border border-[var(--color-brand-border)]">
                                            <span className="w-2 h-2 rounded-full bg-slate-500"></span>
                                            <span className="font-semibold text-[var(--color-brand-text-primary)]">{step.parent2?.name}</span>
                                        </div>
                                        </div>

                                        {/* Arrow */}
                                        <div className="rotate-90 md:rotate-0 text-[var(--color-brand-text-muted)]">
                                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
                                        </div>

                                        {/* Result */}
                                        <div className="flex items-center gap-3 flex-1 justify-start w-full md:w-auto">
                                        <div className="flex items-center gap-2 bg-[var(--color-brand-primary)]/10 px-4 py-2 rounded-lg border border-[var(--color-brand-primary)]/30 w-full md:w-auto justify-center md:justify-start">
                                            <span className="text-xl">🥚</span>
                                            <span className="font-bold text-[var(--color-brand-primary)]">{step.result.name}</span>
                                        </div>
                                        </div>

                                    </div>
                                    </div>
                                </div>
                                ))}

                                <div className="relative mt-8">
                                    <div className="absolute -left-[43px] top-1/2 -translate-y-1/2 w-8 h-8 rounded-full bg-green-900/50 border-2 border-green-500 flex items-center justify-center font-bold text-green-400 z-10">
                                        ✓
                                    </div>
                                    <div className="bg-green-900/10 border border-green-500/20 p-4 rounded-xl text-green-400 font-bold flex items-center gap-3">
                                        <span>Target Reached!</span>
                                        <span className="text-sm opacity-70 font-normal">Now breed for passives.</span>
                                    </div>
                                </div>
                            </div>
                        ) : (
                            <div className="bg-[var(--color-brand-bg-main)] rounded-xl p-4 border border-[var(--color-brand-border)] overflow-hidden">
                                <BreedingTree steps={path} targetKey={targetKey} />
                            </div>
                        )
                    )}
                </div>
            )}
          </div>
        </div>
      </div>

      <p className="text-xs text-[var(--color-brand-text-muted)] text-center pt-4 border-t border-[var(--color-brand-border)]">
        Breeding outcome data adapted from{' '}
        <a
          href="https://github.com/mlg404/palworld-paldex-api"
          target="_blank"
          rel="noopener noreferrer"
          className="underline hover:text-[var(--color-brand-text-secondary)]"
        >
          mlg404/palworld-paldex-api
        </a>{' '}
        (MIT).
      </p>
    </div>
  );
}
