// AUTO-GENERATED by tier-list-from-data skill. Do not edit by hand.
// Regenerate with derive_tiers.py.

export type Tier = "S" | "A" | "B" | "C" | "D";

export interface TierEntry {
  rank: Tier;
  key: string;
  score: number;
  note?: string;
}

export interface TierCategory {
  key: string;
  category: string;
  description: string;
  entries: TierEntry[];
}

export const tiers: TierCategory[] = [
  {
    "key": "mining",
    "category": "Top Mining Pals",
    "description": "Best picks for ore farms. Suitability is weighted heavily; melee attack breaks ties between equal-level workers.",
    "entries": [
      {
        "rank": "S",
        "key": "Blazamut",
        "score": 4075.0,
        "note": "Lv4 mining and 150 melee — top stats in the role."
      },
      {
        "rank": "S",
        "key": "Blazamut_Ryu",
        "score": 4075.0,
        "note": "Dragon/Fire variant of Blazamut, same Lv4 mining with slightly better defenses."
      },
      {
        "rank": "A",
        "key": "Astegon",
        "score": 4050.0,
        "note": "Lv4 mining specialist. Dragon/Dark typing makes it a flexible breeding parent."
      },
      {
        "rank": "A",
        "key": "Knocklem",
        "score": 4050.0,
        "note": "Lv4 mining plus Lv4 transporting — runs an ore farm by itself."
      },
      {
        "rank": "A",
        "key": "Cryolinx_Terra",
        "score": 3070.0,
        "note": "Lv3 mining; weaker than the Lv4 picks but adds gathering and transport coverage."
      },
      {
        "rank": "A",
        "key": "Anubis",
        "score": 3065.0,
        "note": "Lv3 mining but the best generalist on the list — also S-tier handiwork."
      },
      {
        "rank": "A",
        "key": "Reptyro",
        "score": 3050.0,
        "note": "Lv3 mining mid-game pick. Easier to acquire than the legendaries above."
      },
      {
        "rank": "B",
        "key": "Reptyro_Cryst",
        "score": 3050.0
      },
      {
        "rank": "B",
        "key": "Warsect_Terra",
        "score": 3050.0
      },
      {
        "rank": "B",
        "key": "Menasting",
        "score": 3050.0
      },
      {
        "rank": "B",
        "key": "Menasting_Terra",
        "score": 3050.0
      },
      {
        "rank": "B",
        "key": "Xenogard",
        "score": 3050.0
      }
    ]
  },
  {
    "key": "handiwork",
    "category": "Top Handiwork Pals",
    "description": "Crafting bench priority. Handiwork level dominates; melee attack matters for hammers.",
    "entries": [
      {
        "rank": "S",
        "key": "Anubis",
        "score": 4039.0,
        "note": "Lv4 handiwork. The universal pick — strong combat stats on top of it."
      },
      {
        "rank": "S",
        "key": "Selyne",
        "score": 4030.0,
        "note": "Lv4 handiwork plus Lv3 medicine — covers two crafting workflows."
      },
      {
        "rank": "S",
        "key": "Splatterina",
        "score": 4030.0,
        "note": "Lv4 handiwork specialist. Dark typing for late-game compositions."
      },
      {
        "rank": "S",
        "key": "Verdash",
        "score": 3030.0,
        "note": "Lv3 handiwork but five other work skills — the multitool early-game pick."
      },
      {
        "rank": "S",
        "key": "Lyleen",
        "score": 3030.0,
        "note": "Lv3 handiwork plus Lv4 planting and Lv3 medicine. Classic base anchor."
      },
      {
        "rank": "A",
        "key": "Lyleen_Noct",
        "score": 3030.0,
        "note": "Dark variant of Lyleen, same Lv3 handiwork with stronger defenses."
      },
      {
        "rank": "A",
        "key": "Dogen",
        "score": 3030.0,
        "note": "Lv3 handiwork with broad coverage; great early base utility."
      },
      {
        "rank": "A",
        "key": "Nitemary",
        "score": 3030.0,
        "note": "Lv3 handiwork dark variant."
      },
      {
        "rank": "A",
        "key": "Nyafia",
        "score": 3030.0,
        "note": "Lv3 handiwork with gathering and lumbering."
      },
      {
        "rank": "A",
        "key": "Lunaris",
        "score": 3024.0,
        "note": "Lv3 handiwork early-mid game generalist."
      },
      {
        "rank": "A",
        "key": "Wixen",
        "score": 3015.0,
        "note": "Lv3 handiwork plus Lv2 kindling — covers crafting and cooking."
      },
      {
        "rank": "A",
        "key": "Wixen_Noct",
        "score": 3015.0,
        "note": "Dark variant of Wixen, same Lv3 handiwork."
      }
    ]
  },
  {
    "key": "lumbering",
    "category": "Top Lumbering Pals",
    "description": "Wood production. Suitability level wins; attack breaks ties.",
    "entries": [
      {
        "rank": "S",
        "key": "Celesdir",
        "score": 4040.0,
        "note": "Lv4 lumbering top pick."
      },
      {
        "rank": "S",
        "key": "Hartalis",
        "score": 4040.0,
        "note": "Lv4 lumbering with 135 HP and Lv3 gathering — durable and versatile."
      },
      {
        "rank": "S",
        "key": "Bushi",
        "score": 3040.0,
        "note": "Lv3 lumbering with strong attack; doubles as a combat pal."
      },
      {
        "rank": "A",
        "key": "Bushi_Noct",
        "score": 3040.0,
        "note": "Dark variant of Bushi, same Lv3 lumbering with slightly better ranged."
      },
      {
        "rank": "A",
        "key": "Wumpo",
        "score": 3040.0,
        "note": "Lv3 lumbering plus Lv4 transporting — moves wood as well as cutting it."
      },
      {
        "rank": "A",
        "key": "Wumpo_Botan",
        "score": 3040.0,
        "note": "Grass variant of Wumpo, same Lv3 lumbering and Lv4 transport."
      },
      {
        "rank": "A",
        "key": "Warsect",
        "score": 3040.0,
        "note": "Lv3 lumbering with high HP and defense; fights back when raided."
      },
      {
        "rank": "A",
        "key": "Prixter",
        "score": 3040.0,
        "note": "Lv3 lumbering Dark/Ground specialist."
      },
      {
        "rank": "B",
        "key": "Silvegis",
        "score": 3040.0
      },
      {
        "rank": "B",
        "key": "Bastigor",
        "score": 3040.0
      },
      {
        "rank": "B",
        "key": "Cryolinx",
        "score": 2056.0
      },
      {
        "rank": "B",
        "key": "Cryolinx_Terra",
        "score": 2056.0
      }
    ]
  },
  {
    "key": "kindling",
    "category": "Top Kindling Pals",
    "description": "Cooking and forging. Suitability level decides; support stat reflects work efficiency.",
    "entries": [
      {
        "rank": "S",
        "key": "Jormuntide_Ignis",
        "score": 4030.0,
        "note": "Lv4 kindling on a Dragon/Fire body with 150 melee — best dual-use in the role."
      },
      {
        "rank": "S",
        "key": "Blazamut_Ryu",
        "score": 4015.0,
        "note": "Lv4 kindling and Lv4 mining on one pal."
      },
      {
        "rank": "A",
        "key": "Ragnahawk",
        "score": 3030.0,
        "note": "Lv3 kindling plus Lv3 transporting — flying utility."
      },
      {
        "rank": "A",
        "key": "Blazehowl",
        "score": 3030.0,
        "note": "Lv3 kindling with combat utility; easier to obtain than legendaries."
      },
      {
        "rank": "A",
        "key": "Blazehowl_Noct",
        "score": 3030.0,
        "note": "Dark variant of Blazehowl, same Lv3 kindling."
      },
      {
        "rank": "B",
        "key": "Reptyro",
        "score": 3030.0
      },
      {
        "rank": "B",
        "key": "Suzaku",
        "score": 3030.0
      },
      {
        "rank": "B",
        "key": "Sootseer",
        "score": 3030.0
      },
      {
        "rank": "B",
        "key": "Ghangler_Ignis",
        "score": 3030.0
      },
      {
        "rank": "B",
        "key": "Whalaska_Ignis",
        "score": 3030.0
      },
      {
        "rank": "B",
        "key": "Faleris",
        "score": 3027.0
      },
      {
        "rank": "B",
        "key": "Blazamut",
        "score": 3015.0
      }
    ]
  },
  {
    "key": "watering",
    "category": "Top Watering Pals",
    "description": "Hydration and berry plantations. Higher level = faster water generation.",
    "entries": [
      {
        "rank": "S",
        "key": "Jormuntide",
        "score": 4030.0,
        "note": "Lv4 watering on a 150-melee Dragon body. The meta legend."
      },
      {
        "rank": "S",
        "key": "Ghangler",
        "score": 4030.0,
        "note": "Lv4 watering plus transport — great support for berry plantations."
      },
      {
        "rank": "A",
        "key": "Ghangler_Ignis",
        "score": 4030.0,
        "note": "Lv4 watering and Lv3 kindling on the same pal — rare dual workload."
      },
      {
        "rank": "A",
        "key": "Neptilius",
        "score": 4030.0,
        "note": "Lv4 watering specialist with 145 ranged attack."
      },
      {
        "rank": "A",
        "key": "Faleris_Aqua",
        "score": 4027.0,
        "note": "Lv4 watering plus Lv3 transporting; flying mount candidate."
      },
      {
        "rank": "A",
        "key": "Broncherry_Aqua",
        "score": 3036.0,
        "note": "Lv3 watering with high HP and support — budget pick."
      },
      {
        "rank": "B",
        "key": "Elphidran_Aqua",
        "score": 3030.0
      },
      {
        "rank": "B",
        "key": "Azurobe",
        "score": 3030.0
      },
      {
        "rank": "B",
        "key": "Suzaku_Aqua",
        "score": 3030.0
      },
      {
        "rank": "B",
        "key": "Whalaska",
        "score": 3030.0
      },
      {
        "rank": "B",
        "key": "Penking",
        "score": 2030.0
      },
      {
        "rank": "B",
        "key": "Penking_Lux",
        "score": 2030.0
      }
    ]
  },
  {
    "key": "melee-combat",
    "category": "Best Melee Combat Pals",
    "description": "Boss fights and close-range DPS. Attack dominates; HP and defense weight for survivability.",
    "entries": [
      {
        "rank": "S",
        "key": "Blazamut_Ryu",
        "score": 265.0,
        "note": "150 melee, 130 ranged, 125 defense — top damage and survivability."
      },
      {
        "rank": "S",
        "key": "Jormuntide",
        "score": 265.0,
        "note": "150 melee on a 130 HP Dragon — best raw stats in the role."
      },
      {
        "rank": "S",
        "key": "Jormuntide_Ignis",
        "score": 265.0,
        "note": "150 melee Dragon/Fire variant; identical scores to base."
      },
      {
        "rank": "S",
        "key": "Blazamut",
        "score": 260.0,
        "note": "150 melee with 120 defense; the OG melee meta pick."
      },
      {
        "rank": "S",
        "key": "Shadowbeak",
        "score": 260.0,
        "note": "130 melee, 140 defense — both bruiser and tank."
      },
      {
        "rank": "S",
        "key": "Paladius",
        "score": 247.5,
        "note": "Lower attack but 145 defense and 130 HP — fights forever."
      },
      {
        "rank": "S",
        "key": "Cryolinx",
        "score": 245.0,
        "note": "140 melee Ice-type with cooling utility at base."
      },
      {
        "rank": "S",
        "key": "Cryolinx_Terra",
        "score": 245.0,
        "note": "Ground variant; same 140 melee with mining synergy."
      },
      {
        "rank": "S",
        "key": "Incineram",
        "score": 240.0,
        "note": "150 melee Fire/Dark glass cannon."
      },
      {
        "rank": "S",
        "key": "Incineram_Noct",
        "score": 240.0,
        "note": "Pure Dark Incineram — same 150 melee with slight defensive trade."
      },
      {
        "rank": "S",
        "key": "Anubis",
        "score": 240.0,
        "note": "Best generalist on the list; combat-grade stats plus S-tier handiwork."
      },
      {
        "rank": "S",
        "key": "Frostallion_Noct",
        "score": 237.5,
        "note": "Tankiest dragon in the list; high HP and defense plus dark damage."
      }
    ]
  },
  {
    "key": "ranged-combat",
    "category": "Best Ranged Combat Pals",
    "description": "Kiting bosses and elemental damage. Ranged attack dominates; HP weights for survivability.",
    "entries": [
      {
        "rank": "S",
        "key": "Frostallion_Noct",
        "score": 236.5,
        "note": "140 ranged, 135 defense, 140 HP — the all-rounder."
      },
      {
        "rank": "S",
        "key": "Necromus",
        "score": 233.0,
        "note": "145 ranged Dark Horse; partner skill boosts dark damage."
      },
      {
        "rank": "S",
        "key": "Frostallion",
        "score": 232.0,
        "note": "Ice legendary, same 140 ranged with weaker defense than the Noct variant."
      },
      {
        "rank": "S",
        "key": "Bellanoir",
        "score": 228.0,
        "note": "150 ranged raid-boss-grade Dark pal."
      },
      {
        "rank": "S",
        "key": "Bellanoir_Libero",
        "score": 228.0,
        "note": "Libero variant; identical 150 ranged with raid utility."
      },
      {
        "rank": "S",
        "key": "Neptilius",
        "score": 224.5,
        "note": "145 ranged Water pal with strong defenses."
      },
      {
        "rank": "S",
        "key": "Bastigor",
        "score": 222.0,
        "note": "Ice/Dragon with 130 ranged and 140 HP — great mount candidate."
      },
      {
        "rank": "S",
        "key": "Jetragon",
        "score": 217.0,
        "note": "140 ranged plus the fastest mount in the game."
      },
      {
        "rank": "S",
        "key": "Hartalis",
        "score": 217.0,
        "note": "Dragon with 130 ranged plus Lv4 lumbering — work AND fight."
      },
      {
        "rank": "S",
        "key": "Paladius",
        "score": 215.5,
        "note": "Holy knight: 120 ranged but unmatched survival stats."
      },
      {
        "rank": "S",
        "key": "Jormuntide_Ignis",
        "score": 212.0,
        "note": "130 ranged on top of meta-tier melee."
      },
      {
        "rank": "S",
        "key": "Shadowbeak",
        "score": 210.0,
        "note": "Tank-shaped pal with 120 ranged and 140 defense."
      }
    ]
  },
  {
    "key": "tank",
    "category": "Best Tank Pals",
    "description": "Damage soaks for solo play. HP and defense win; melee attack is a tiebreaker so they can fight back.",
    "entries": [
      {
        "rank": "S",
        "key": "Paladius",
        "score": 479.0,
        "note": "145 defense and 130 HP — top defensive stat line in the dex."
      },
      {
        "rank": "S",
        "key": "Frostallion_Noct",
        "score": 468.0,
        "note": "140 HP, 135 defense, plus 140 ranged to fight back."
      },
      {
        "rank": "S",
        "key": "Shadowbeak",
        "score": 463.0,
        "note": "120 HP and 140 defense — solid HP/defense balance."
      },
      {
        "rank": "S",
        "key": "Frostallion",
        "score": 438.0,
        "note": "140 HP and 120 defense; weaker than the Noct variant."
      },
      {
        "rank": "S",
        "key": "Bastigor",
        "score": 438.0,
        "note": "140 HP Ice tank with mining utility."
      },
      {
        "rank": "S",
        "key": "Necromus",
        "score": 426.0,
        "note": "130 HP, 120 defense, partner skill survivability."
      },
      {
        "rank": "S",
        "key": "Knocklem",
        "score": 426.0,
        "note": "Ground tank with Lv4 mining — base AND raid use."
      },
      {
        "rank": "S",
        "key": "Xenolord",
        "score": 426.0,
        "note": "Endgame Dark/Dragon raid pal."
      },
      {
        "rank": "S",
        "key": "Braloha",
        "score": 426.0,
        "note": "130 HP with Lv4 planting and gathering — multi-role base tank."
      },
      {
        "rank": "S",
        "key": "Reptyro_Cryst",
        "score": 422.0,
        "note": "Crystal variant; 130 defense plus Lv3 mining and cooling."
      }
    ]
  }
];
